"""Initial tables

Revision ID: 505698ac377e
Revises: 
Create Date: 2025-06-01 12:49:09.148233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505698ac377e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_url', sa.Text(), nullable=False),
    sa.Column('css_selector', sa.Text(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('proxy_enabled', sa.Boolean(), nullable=True),
    sa.Column('schedule_cron', sa.String(length=100), nullable=False),
    sa.Column('gemini_prompt', sa.Text(), nullable=False),
    sa.Column('gemini_model', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('wait_time', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('extra_config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_configs_id'), 'scrape_configs', ['id'], unique=False)
    op.create_index(op.f('ix_scrape_configs_name'), 'scrape_configs', ['name'], unique=True)
    op.create_table('scrape_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('gemini_response', sa.JSON(), nullable=True),
    sa.Column('gemini_cost', sa.Float(), nullable=True),
    sa.Column('gemini_model_used', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['scrape_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_results_id'), 'scrape_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scrape_results_id'), table_name='scrape_results')
    op.drop_table('scrape_results')
    op.drop_index(op.f('ix_scrape_configs_name'), table_name='scrape_configs')
    op.drop_index(op.f('ix_scrape_configs_id'), table_name='scrape_configs')
    op.drop_table('scrape_configs')
    # ### end Alembic commands ###